### Test 1: Home route 
GET http://localhost:8080/

### Test 2: Get ALL Contacts
GET http://localhost:8080/contacts

###

### Test 3: Get a SINGLE Contact 
GET http://localhost:8080/contacts/6a47ca14212149a8d9bd277b
